# Generated by Django 5.2.13 on 2026-05-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprediction',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
