# Generated by Django 5.2.13 on 2026-05-09 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_chatsession_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('analyze', 'Analyze')], max_length=10)),
                ('kind', models.CharField(choices=[('department', 'Department'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('appointment', 'Appointment'), ('prediction', 'AI Prediction')], max_length=15)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='hospital_au_created_41bb18_idx'), models.Index(fields=['kind'], name='hospital_au_kind_fd5626_idx')],
            },
        ),
    ]
